### ISSUE TITLE
can we add blockchain to it?

### ISSUE THREAD

**Issue by Yhodhan** [fkrause98/haskell-edsl#1]
hello i have seen the repo and it looks amazing, have you considered to add the Cardano blockchin into it? as it is also written in haskell integration should be fair easy and straight.

**Comment by Clarevero1** [comment]
> hello i have seen the repo and it looks amazing, have you considered to add the Cardano blockchin into it? as it is also written in haskell integration should be fair easy and straight.

Were you able to get it now ?

**Comment by fkrause98** [comment]
Won't fix.
